discord:
  token: "" # discord bot token
  guild_id: "" # target guild id
  chat_id: "" # target channel id
  webhook_url: "" # discord webhook url

settings:
  activity:
    enable: true
    context: "Minecord" # activity string

color:
  default: 0x77C4A3
  join: 0x00DD00
  quit: 0xDD0000
  death: 0x3E3E3E
  kick: 0x2D2D2D

format: # Mini message format
  user_join: "<user>님이 게임에 접속했어요. <currentplayer>/<maxplayer>"
  user_quit: "<user>님이 게임에서 나갔어요. <currentplayer>/<maxplayer>"
  forbidden_channel: "설정된 채널에서만 이 명령어를 사용하실 수 있어요"
  discord_user_chat: "<user>: <message>"