token: "" # The discord bot token
channelId: "" # The id of main channel

invite_url: ""

show_activity: true
server_address: ""

messageFormat: "<<light_purple><sender><reset>> <message>" # EX) <light_purple><sender><reset> : <message>

customColor: false
supportMarkdown: true

styleOnlineCommand: 0
NoMemberMessage: "사람이 없습니다."

# Customizing is possible with Style 1.
embedColor: 0x0070ff
embedTitle: ":notepad_spiral: **온라인 유저**"
embedField1: "인원:"
embedField2: "목록:"

# Formatter used to send from Minecraft Server to Discord
startMessage: ":white_check_mark: **서버가 시작 되었습니다.**"
stopMessage: ":stop_sign: **서버가 종료 되었습니다.**"

chatFormat: "**<player>**: <message>"
chatEmbedColor: 0x0070ff
chatEmbedTitle: "**온라인 유저**"

accessEnable: true
joinFormat: "<player>님이 게임에 들어왔습니다. 현재 플레이어 수: <online>/<max>명"
leaveFormat: "<player>님이 게임에서 나갔습니다. 현재 플레이어 수: <online>/<max>명"
joinEmbed: false
leaveEmbed: false
joinEmbedColor: 0x43b581
leaveEmbedColor: 0xc14243
joinEmbedTitle: ""
leaveEmbedTitle: ""

deathEnable: true
deathFormat: "<player>님이 사망 하셨습니다."
deathEmbed: false
deathEmbedColor: 0x0
deathEmbedTitle: ""

kickEnable: true
kickFormat: "<player>님이 추방 되었습니다."
kickEmbed: false
kickEmbedColor: 0xc14243
kickEmbedTitle: ""