name: ${project.name}
version: ${project.version}
api-version: 1.16
main: xyz.netherald.wild.discord.WildDiscord

commands:
  d_op:
    description: OP command
    usage: /d_op <discord_id>

  d_deop:
    description: DEOP command
    usage: /d_deop <discord_id>

  d_gamerule:
    description: GAMERULE command
    usage: /d_gamerule <rule> <boolean>