name: ${rootProject.name}
version: ${rootProject.version}
api-version: 1.19
main: dev.cube1.minecord.plugin.CorePlugin

libraries:
  - net.dv8tion:JDA:5.0.0-alpha.21
  - org.jetbrains.kotlin:kotlin-stdlib:1.7.20
  - org.jetbrains.kotlin:kotlin-reflect:1.7.20
  - org.jetbrains.exposed:exposed-core:0.39.2
  - org.jetbrains.exposed:exposed-jdbc:0.39.2
  - io.github.monun:kommand-core:2.14.0